#!/usr/bin/env python3
"""Reference-latent method sweep — Sprint 4 Prompt 16.

For the single known-difficult shot from the Prompt 15.1 live GPU
result (timeline index 2 — where a duplicated diagonal spear/polearm
still appeared alongside the correct dragon-headed halberd), isolates
exactly one variable: `reference_latents_method`. Three candidates —
offset, uxo/uno, index_timestep_zero — are each generated once, all
sharing the identical anchor, the identical unmodified Prompt 15.1
shot-2 prompt, and the identical seed (981216397 for the sample fight).
The already-paid Prompt 15.1 shot-2 result is this experiment's
implicit "index" control and is never regenerated.

Never generates a T2I anchor, never runs Wan, never concatenates video
— exactly 3 ComfyUI jobs (one per candidate method).

See products/chess2fight/rendering/reference_method_calibration.py for
the underlying implementation, and
products/chess2fight/rendering/workflows/README-reference-method-sweep.md
for the three experimental workflow files' own provenance.

Usage:
    # Dry run — no ComfyUI/network calls, uses an existing anchor PNG.
    python scripts/render_reference_method_calibration.py \\
        --sample --anchor-path path/to/frame0001.png \\
        --anchor-original-seed 1697950441 --seed 981216397 --dry-run

    # Real run.
    python scripts/render_reference_method_calibration.py \\
        --sample --anchor-path path/to/frame0001.png \\
        --anchor-original-seed 1697950441 --seed 981216397

Requires IMAGE_PROVIDER=comfyui and COMFYUI_BASE_URL — reference-
conditioning has no mock equivalent, same reasoning as
render_reference_seed_calibration.py. animation_provider is never
checked here at all — this experiment never touches Wan.
"""

from __future__ import annotations

import argparse
import asyncio
import hashlib
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from core.ai_router import get_ai_provider  # noqa: E402
from core.config import get_settings  # noqa: E402
from products.chess2fight.rendering.acceptance_preflight import (  # noqa: E402
    check_output_writability,
    check_reference_method_node_availability,
    preflight_check,
)
from products.chess2fight.rendering.reference_method_calibration import (  # noqa: E402
    CANDIDATE_METHODS,
    ReferenceMethodCalibrationPlan,
    ReferenceMethodCalibrationRunner,
    method_workflow_path,
)
from products.chess2fight.rendering.reference_seed_calibration import AnchorValidationError  # noqa: E402
from products.chess2fight.schemas import BattleMode, BattlePreferences  # noqa: E402

SAMPLE_PGN_PATH = Path(__file__).resolve().parent.parent / (
    "products/chess2fight/rendering/fixtures/sample_acceptance_game.pgn"
)

DEFAULT_MANIFEST_PATH = "reference_method_calibration_manifest.json"


def _parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    pgn_source = parser.add_mutually_exclusive_group()
    pgn_source.add_argument("--pgn", type=str, help="PGN text directly on the command line.")
    pgn_source.add_argument("--pgn-file", type=str, help="Path to a .pgn file.")
    pgn_source.add_argument(
        "--sample", action="store_true", help=f"Use the bundled sample game ({SAMPLE_PGN_PATH.name})."
    )
    parser.add_argument(
        "--anchor-path", type=str, required=True,
        help="Path to an EXISTING canonical anchor image. Never generated by this script.",
    )
    parser.add_argument(
        "--anchor-original-seed", type=int, required=True,
        help="The anchor's own historical generation seed, for evidence traceability.",
    )
    parser.add_argument(
        "--seed", type=int, required=True,
        help="The single seed every candidate must use — 981216397 for the sample fight's shot 2. "
        "Never re-derived per candidate.",
    )
    parser.add_argument(
        "--timeline-index", type=int, default=2,
        help="Which single timeline shot to reference-condition. Default: 2 — the known-difficult "
        "Prompt 15.1 shot.",
    )
    parser.add_argument(
        "--control-image", type=str, default=None,
        help="Optional path to the already-paid Prompt 15.1 shot-2 output, for manifest evidence only — "
        "never read for validation, never regenerated.",
    )
    parser.add_argument("--style", type=str, default="anime", help="Visual/narrative style. Default: anime.")
    parser.add_argument(
        "--battle-mode", type=str, default="duel", choices=[m.value for m in BattleMode],
        help="Battle mode. Default: duel.",
    )
    parser.add_argument(
        "--manifest-path", type=str, default=DEFAULT_MANIFEST_PATH,
        help=f"Where to write the calibration manifest after a successful run. Default: {DEFAULT_MANIFEST_PATH}.",
    )
    parser.add_argument(
        "--dry-run", action="store_true",
        help="Validate the anchor and print the plan only — make no ComfyUI/network calls, write no manifest.",
    )
    parser.add_argument(
        "--skip-preflight", action="store_true", help="Skip the pre-generation preflight checks.",
    )
    return parser.parse_args()


def _resolve_pgn(args: argparse.Namespace) -> str:
    if args.pgn:
        return args.pgn
    if args.pgn_file:
        return Path(args.pgn_file).read_text(encoding="utf-8")
    if args.sample:
        return SAMPLE_PGN_PATH.read_text(encoding="utf-8")
    print("ERROR: one of --pgn, --pgn-file, or --sample is required.", file=sys.stderr)
    sys.exit(1)


def _print_plan_summary(plan: ReferenceMethodCalibrationPlan) -> None:
    print("=== Reference-latent method sweep plan ===")
    print(f"timeline index: {plan.timeline_index}")
    print(f"canonical anchor: {plan.anchor.path}")
    print(f"anchor sha256: {plan.anchor.sha256}")
    print(f"anchor dimensions: {plan.anchor.width}x{plan.anchor.height}")
    print()
    print(f"prompt: {plan.prompt}")
    print()
    print(f"seed: {plan.planned_seed}")
    print()
    print("existing control:")
    print(f"  {plan.control.method}")
    print(f"  NOT regenerated (generated_this_run={plan.control.generated_this_run})")
    if plan.control.control_image_path:
        print(f"  control image: {plan.control.control_image_path}")
    print()
    print("candidate methods:")
    for candidate in plan.candidates:
        print(f"  {candidate.method}  (workflow: {candidate.workflow_path})")
    print()
    seeds = {plan.planned_seed}
    print(f"same anchor for every candidate: {'YES'}")
    print(f"same prompt for every candidate: {'YES'}")
    print(f"same seed for every candidate: {'YES' if len(seeds) == 1 else 'NO'}")
    print()
    print(f"expected ComfyUI jobs: {plan.expected_comfyui_jobs}")
    print("T2I jobs: 0")
    print("Wan jobs: 0")
    print("VideoBuilder: disabled")


def _write_manifest(manifest_path: str, plan: ReferenceMethodCalibrationPlan, result) -> None:
    manifest = {
        "anchor_path": plan.anchor.path,
        "anchor_sha256": plan.anchor.sha256,
        "anchor_original_seed": plan.anchor.original_seed,
        "timeline_index": plan.timeline_index,
        "prompt": plan.prompt,
        "planned_seed": plan.planned_seed,
        "control": {
            "method": plan.control.method,
            "generated_this_run": plan.control.generated_this_run,
            "seed": plan.control.seed,
            "control_image_path": plan.control.control_image_path,
            "control_image_sha256": plan.control.control_image_sha256,
        },
        "candidates": [
            {
                "method": r.method,
                "workflow_path": r.workflow_path,
                "planned_seed": r.planned_seed,
                "actual_seed": r.actual_seed,
                "output_path": r.output_path,
                "provider": "comfyui",
                "model": "flux-2-klein-4b.safetensors",
                "width": plan.anchor.width,
                "height": plan.anchor.height,
            }
            for r in result.candidate_results
        ],
        "expected_comfyui_jobs": plan.expected_comfyui_jobs,
    }
    Path(manifest_path).write_text(json.dumps(manifest, indent=2), encoding="utf-8")


async def _main() -> int:
    args = _parse_args()
    pgn = _resolve_pgn(args)

    settings = get_settings()
    ai_provider = get_ai_provider()
    runner = ReferenceMethodCalibrationRunner(ai_provider)

    preferences = BattlePreferences(battle_mode=BattleMode(args.battle_mode), style=args.style)

    control_image_sha256 = None
    if args.control_image is not None:
        # Read only for a SHA256, purely for manifest evidence — never
        # validated, never treated as this run's own anchor, never
        # used in any generation call.
        try:
            control_image_sha256 = hashlib.sha256(Path(args.control_image).read_bytes()).hexdigest()
        except OSError as exc:
            print(f"ERROR: could not read --control-image ({exc}).", file=sys.stderr)
            return 1

    try:
        plan = await runner.prepare(
            pgn, preferences, anchor_path=args.anchor_path, anchor_original_seed=args.anchor_original_seed,
            seed=args.seed, style=args.style, battle_mode=args.battle_mode, timeline_index=args.timeline_index,
            control_image_path=args.control_image, control_image_sha256=control_image_sha256,
        )
    except AnchorValidationError as exc:
        print(f"ERROR: anchor validation failed — {exc}", file=sys.stderr)
        print("0 paid jobs were attempted.", file=sys.stderr)
        return 1
    except Exception as exc:
        print(f"ERROR during orchestration: {exc}", file=sys.stderr)
        return 1

    _print_plan_summary(plan)

    if args.dry_run:
        print("\nDry run complete — no ComfyUI/network calls were made, no manifest written.")
        return 0

    # No mock equivalent exists for reference-conditioning.
    if settings.image_provider != "comfyui":
        print(
            f"\nERROR: image_provider is {settings.image_provider!r}, not 'comfyui'. Reference-conditioned "
            "generation has no mock equivalent — set IMAGE_PROVIDER=comfyui and COMFYUI_BASE_URL before "
            "running this script for real.",
            file=sys.stderr,
        )
        return 1

    if not args.skip_preflight:
        manifest_parent = str(Path(args.manifest_path).parent) or "."
        writability_problems = check_output_writability([settings.render_storage_root, manifest_parent])
        if writability_problems:
            print("\nPreflight check failed — refusing to start generation:", file=sys.stderr)
            for problem in writability_problems:
                print(f"  - {problem}", file=sys.stderr)
            return 1

        for candidate_path in [method_workflow_path(m) for m in CANDIDATE_METHODS]:
            if not Path(candidate_path).exists():
                print(f"\nPreflight check failed: experimental workflow file not found: {candidate_path}", file=sys.stderr)
                return 1

        problems, preflight_warnings = await preflight_check(settings, check_reference_workflow=True)
        for warning in preflight_warnings:
            print(f"WARNING: {warning}", file=sys.stderr)
        if problems:
            print("\nPreflight check failed — refusing to start generation:", file=sys.stderr)
            for problem in problems:
                print(f"  - {problem}", file=sys.stderr)
            return 1

        method_problems = await check_reference_method_node_availability(settings, list(CANDIDATE_METHODS))
        if method_problems:
            print("\nPreflight check failed — refusing to start generation:", file=sys.stderr)
            for problem in method_problems:
                print(f"  - {problem}", file=sys.stderr)
            return 1

    print(f"\nGenerating {plan.expected_comfyui_jobs} reference-conditioned candidates (0 T2I, 0 Wan)...")
    try:
        result = await runner.execute(plan)
    except Exception as exc:
        print(f"\nERROR during generation: {exc}", file=sys.stderr)
        print(
            "\nAny candidate whose generation completed before this failure remains on disk — nothing is "
            "deleted or replaced by a fake artifact on failure. Never substituting another method, never "
            "falling back to default index, never regenerating the anchor or the existing control.",
            file=sys.stderr,
        )
        return 1

    for r in result.candidate_results:
        print(f"{r.method}: {r.output_path} (seed {r.actual_seed})")

    _write_manifest(args.manifest_path, plan, result)
    print(f"manifest written: {args.manifest_path}")
    return 0


if __name__ == "__main__":
    sys.exit(asyncio.run(_main()))
