#!/usr/bin/env python3
"""Reference-conditioning seed calibration experiment — Sprint 4 Prompt 14.

Isolates exactly one variable from the live Prompt 13.1 GPU result
(which found reference conditioning solved identity but over-locked
composition — measured whole-image SSIM 0.94-0.99 between the anchor
and both reference shots): shared FLUX seed -> per-shot DERIVED FLUX
seed, holding everything else fixed (the same supplied anchor, the
same unmodified Prompt 13 reference-edit prompts, the same workflow,
model, and resolution).

Never generates a T2I anchor, never runs Wan, never concatenates video
— exactly 2 ComfyUI jobs (both reference-conditioned FLUX), the
smallest possible test of this one variable.

See products/chess2fight/rendering/reference_seed_calibration.py for
the underlying implementation and design notes.

Usage:
    # Dry run — no ComfyUI/network calls, uses an existing anchor PNG.
    python scripts/render_reference_seed_calibration.py \\
        --sample --anchor-path path/to/frame0001.png \\
        --anchor-original-seed 1697950441 --dry-run

    # Real run.
    python scripts/render_reference_seed_calibration.py \\
        --sample --anchor-path path/to/frame0001.png \\
        --anchor-original-seed 1697950441

Requires IMAGE_PROVIDER=comfyui and COMFYUI_BASE_URL to be set for a
real run — reference-conditioning has no mock equivalent, same
reasoning as scripts/render_reference_continuity_acceptance.py.
animation_provider is never checked here at all — this experiment
never touches Wan.
"""

from __future__ import annotations

import argparse
import asyncio
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from core.ai_router import get_ai_provider  # noqa: E402
from core.config import get_settings  # noqa: E402
from core.image_providers.comfyui import ComfyUIImageProvider  # noqa: E402
from products.chess2fight.rendering.acceptance_preflight import check_output_writability, preflight_check  # noqa: E402
from products.chess2fight.rendering.reference_seed_calibration import (  # noqa: E402
    AnchorValidationError,
    ReferenceSeedCalibrationPlan,
    ReferenceSeedCalibrationRunner,
)
from products.chess2fight.rendering.visual_continuity import VisualSeedPolicy, build_seed_override  # noqa: E402
from products.chess2fight.schemas import BattleMode, BattlePreferences  # noqa: E402

SAMPLE_PGN_PATH = Path(__file__).resolve().parent.parent / (
    "products/chess2fight/rendering/fixtures/sample_acceptance_game.pgn"
)

DEFAULT_MANIFEST_PATH = "reference_seed_calibration_manifest.json"


def _parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    pgn_source = parser.add_mutually_exclusive_group()
    pgn_source.add_argument("--pgn", type=str, help="PGN text directly on the command line.")
    pgn_source.add_argument("--pgn-file", type=str, help="Path to a .pgn file.")
    pgn_source.add_argument(
        "--sample", action="store_true", help=f"Use the bundled sample game ({SAMPLE_PGN_PATH.name})."
    )
    parser.add_argument(
        "--anchor-path", type=str, required=True,
        help="Path to an EXISTING canonical anchor image (e.g. a real frame0001.png from a prior "
        "acceptance run). Never generated by this script.",
    )
    parser.add_argument(
        "--anchor-original-seed", type=int, required=True,
        help="The anchor's own historical generation seed, for evidence traceability. Never verified "
        "against anything — recorded as-is.",
    )
    parser.add_argument(
        "--shot-indices", type=str, default="1,2",
        help="Comma-separated pair of timeline shot indices to reference-condition. Default: 1,2 — the "
        "same two shots the live Prompt 13.1 GPU run reference-conditioned.",
    )
    parser.add_argument("--style", type=str, default="anime", help="Visual/narrative style. Default: anime.")
    parser.add_argument(
        "--battle-mode", type=str, default="duel", choices=[m.value for m in BattleMode],
        help="Battle mode. Default: duel.",
    )
    parser.add_argument(
        "--manifest-path", type=str, default=DEFAULT_MANIFEST_PATH,
        help=f"Where to write the calibration manifest after a successful run. Default: {DEFAULT_MANIFEST_PATH}.",
    )
    parser.add_argument(
        "--dry-run", action="store_true",
        help="Validate the anchor and print the plan only — make no ComfyUI/network calls, write no manifest.",
    )
    parser.add_argument(
        "--skip-preflight", action="store_true", help="Skip the pre-generation preflight checks.",
    )
    return parser.parse_args()


def _resolve_pgn(args: argparse.Namespace) -> str:
    if args.pgn:
        return args.pgn
    if args.pgn_file:
        return Path(args.pgn_file).read_text(encoding="utf-8")
    if args.sample:
        return SAMPLE_PGN_PATH.read_text(encoding="utf-8")
    print("ERROR: one of --pgn, --pgn-file, or --sample is required.", file=sys.stderr)
    sys.exit(1)


def _print_plan_summary(plan: ReferenceSeedCalibrationPlan) -> None:
    print("=== Reference seed calibration plan ===")
    print(f"canonical anchor:       {plan.anchor.path}")
    print(f"anchor sha256:          {plan.anchor.sha256}")
    print(f"anchor dimensions:      {plan.anchor.width}x{plan.anchor.height}")
    print(f"anchor original seed:   {plan.anchor.original_seed}")
    print(f"fight base visual seed: {plan.fight_base_visual_seed}")
    print()
    for shot in plan.shots:
        print(f"shot[{shot.timeline_index}]:")
        print("  reference-conditioned")
        print(f"  planned derived seed: {shot.planned_flux_seed}")
    print()
    seeds = [s.planned_flux_seed for s in plan.shots]
    print(f"same anchor for both: {'YES' if len(plan.selected_shot_indices) > 1 else 'N/A'}")
    print(f"derived seeds differ: {'YES' if len(set(seeds)) == len(seeds) else 'NO'}")
    print(f"expected ComfyUI jobs: {plan.expected_comfyui_jobs}")
    print("Wan jobs: 0")
    print("VideoBuilder: disabled")


def _write_manifest(manifest_path: str, plan: ReferenceSeedCalibrationPlan, result) -> None:
    manifest = {
        "fight_base_visual_seed": plan.fight_base_visual_seed,
        "anchor_path": plan.anchor.path,
        "anchor_sha256": plan.anchor.sha256,
        "anchor_original_seed": plan.anchor.original_seed,
        "selected_shot_indices": plan.selected_shot_indices,
        "shots": [
            {
                "timeline_index": r.timeline_index,
                "shot_id": r.shot_id,
                "reference_anchor_path": r.reference_anchor_path,
                "reference_anchor_sha256": r.reference_anchor_sha256,
                "prompt": r.prompt,
                "planned_flux_seed": r.planned_flux_seed,
                "actual_flux_seed": r.actual_flux_seed,
                "output_path": r.output_path,
            }
            for r in result.shot_results
        ],
        "provider": "comfyui",
        "model": "flux-2-klein-4b.safetensors",
        "workflow": get_settings().comfyui_reference_workflow_path,
        "width": plan.anchor.width,
        "height": plan.anchor.height,
        "expected_comfyui_jobs": plan.expected_comfyui_jobs,
    }
    Path(manifest_path).write_text(json.dumps(manifest, indent=2), encoding="utf-8")


async def _main() -> int:
    args = _parse_args()
    pgn = _resolve_pgn(args)

    try:
        shot_index_parts = [int(x.strip()) for x in args.shot_indices.split(",")]
        if len(shot_index_parts) != 2:
            raise ValueError("exactly two comma-separated indices are required")
        shot_indices = (shot_index_parts[0], shot_index_parts[1])
    except ValueError as exc:
        print(f"ERROR: --shot-indices must be two comma-separated integers, e.g. '1,2' ({exc}).", file=sys.stderr)
        return 1

    settings = get_settings()
    ai_provider = get_ai_provider()
    runner = ReferenceSeedCalibrationRunner(ai_provider)

    preferences = BattlePreferences(battle_mode=BattleMode(args.battle_mode), style=args.style)

    try:
        plan = await runner.prepare(
            pgn, preferences, anchor_path=args.anchor_path, anchor_original_seed=args.anchor_original_seed,
            style=args.style, battle_mode=args.battle_mode, shot_indices=shot_indices,
        )
    except AnchorValidationError as exc:
        print(f"ERROR: anchor validation failed — {exc}", file=sys.stderr)
        print("0 paid jobs were attempted.", file=sys.stderr)
        return 1
    except Exception as exc:
        print(f"ERROR during orchestration: {exc}", file=sys.stderr)
        return 1

    _print_plan_summary(plan)

    if args.dry_run:
        print("\nDry run complete — no ComfyUI/network calls were made, no manifest written.")
        return 0

    # No mock equivalent exists for reference-conditioning. Only
    # image_provider is required here — this experiment never touches
    # Wan/animation at all, so animation_provider is irrelevant to it.
    if settings.image_provider != "comfyui":
        print(
            f"\nERROR: image_provider is {settings.image_provider!r}, not 'comfyui'. Reference-conditioned "
            "generation has no mock equivalent — set IMAGE_PROVIDER=comfyui and COMFYUI_BASE_URL before "
            "running this script for real.",
            file=sys.stderr,
        )
        return 1

    if not args.skip_preflight:
        manifest_parent = str(Path(args.manifest_path).parent) or "."
        writability_problems = check_output_writability([settings.render_storage_root, manifest_parent])
        if writability_problems:
            print("\nPreflight check failed — refusing to start generation:", file=sys.stderr)
            for problem in writability_problems:
                print(f"  - {problem}", file=sys.stderr)
            return 1

        problems, preflight_warnings = await preflight_check(settings, check_reference_workflow=True)
        for warning in preflight_warnings:
            print(f"WARNING: {warning}", file=sys.stderr)
        if problems:
            print("\nPreflight check failed — refusing to start generation:", file=sys.stderr)
            for problem in problems:
                print(f"  - {problem}", file=sys.stderr)
            return 1

    # Sprint 4 Prompt 14: DERIVED policy only — this experiment
    # specifically isolates shared-seed vs. per-shot-derived-seed;
    # SHARED is what the live Prompt 13.1 run already used. Reuses
    # build_seed_override directly (not a hand-written lambda) — "do
    # not duplicate seed logic."
    seed_override = build_seed_override(VisualSeedPolicy.DERIVED, plan.fight_base_visual_seed)
    reference_provider = ComfyUIImageProvider(seed_override=seed_override)

    print(f"\nGenerating {plan.expected_comfyui_jobs} reference-conditioned shots (0 T2I, 0 Wan)...")
    try:
        result = await runner.execute(plan, reference_provider)
    except Exception as exc:
        print(f"\nERROR during generation: {exc}", file=sys.stderr)
        print(
            "\nAny shot whose generation completed before this failure remains on disk — nothing is "
            "deleted or replaced by a fake artifact on failure. This experiment never claims success "
            "after a partial failure.",
            file=sys.stderr,
        )
        return 1

    for r in result.shot_results:
        print(f"shot[{r.timeline_index}]: {r.output_path} (seed {r.actual_flux_seed})")

    _write_manifest(args.manifest_path, plan, result)
    print(f"manifest written: {args.manifest_path}")
    return 0


if __name__ == "__main__":
    sys.exit(asyncio.run(_main()))
