"""ReferenceSeedCalibrationRunner — Sprint 4 Prompt 14.

A low-cost, keyframe-only calibration experiment isolating exactly one
variable: shared vs. per-shot-derived FLUX seed for reference-
conditioned generation. Motivated by the real Prompt 13.1 GPU
evidence, which combined two continuity variables at once (a single
canonical anchor AND a single shared FLUX seed for every reference
generation) and found identity was solved but composition collapsed
(measured whole-image SSIM 0.94-0.99 between the anchor and both
reference shots, vs. 0.36-0.45 for the earlier independent-seed run).
This experiment changes only the seed policy — shared seeds -> per-shot
DERIVED seeds — while holding everything else fixed: the same supplied
anchor, the same Prompt 13 reference-edit prompt composition, the same
workflow, the same model, the same resolution.

    an EXISTING anchor PNG (never generated here)
    -> shot 1: compose_reference_edit_prompt() [UNCHANGED wording]
       + a per-shot DERIVED seed (base_seed, this exact prompt)
       -> ComfyUIImageProvider.generate_reference_conditioned_image()
    -> shot 2: SAME anchor, its OWN reference-edit prompt
       + its OWN per-shot DERIVED seed
       -> ComfyUIImageProvider.generate_reference_conditioned_image()

Explicitly NOT chained (shot1's own output never becomes shot2's
reference) — both calls pass the identical, externally-supplied
anchor path, fixed before either call happens and never reassigned.

No T2I anchor generation, no Wan, no VideoBuilder concatenation —
exactly 2 ComfyUI jobs total, the smallest possible test of this one
variable. Reuses `compose_reference_edit_prompt` (unchanged wording —
this experiment's whole point is isolating the seed variable, not
re-testing prompt composition), `derive_fight_base_visual_seed` /
`derive_shot_seed` (not duplicated), and
`ComfyUIImageProvider.generate_reference_conditioned_image` directly
(no new HTTP client, no new ComfyUI integration code) — the same
production capability Sprint 4 Prompt 13 built and Prompt 13.1 proved
live.
"""

from __future__ import annotations

import hashlib
import logging
import uuid
from pathlib import Path

from PIL import Image
from pydantic import BaseModel, ConfigDict, Field

from core.exceptions import ImageProviderError
from core.image_providers.comfyui import ComfyUIImageProvider
from products.chess2fight.cinematic.prompt_generator import compose_reference_edit_prompt
from products.chess2fight.orchestrator import FightOrchestrator
from products.chess2fight.rendering.asset_manager import AssetManager
from products.chess2fight.rendering.multi_shot_acceptance import SeedEvidenceMismatchError
from products.chess2fight.rendering.visual_continuity import derive_fight_base_visual_seed, derive_shot_seed
from products.chess2fight.schemas import BattlePreferences

logger = logging.getLogger(__name__)

# Sprint 4 Prompt 13's own validated FLUX policy — this calibration
# experiment deliberately changes nothing about resolution (only the
# seed policy is under test), so the supplied anchor is expected to
# already be exactly this size; see AnchorValidationError.
_EXPECTED_ANCHOR_WIDTH = 1280
_EXPECTED_ANCHOR_HEIGHT = 704


class AnchorValidationError(RuntimeError):
    """Raised by `prepare()` if the supplied anchor doesn't exist,
    isn't a valid readable image, or isn't exactly
    `_EXPECTED_ANCHOR_WIDTH`x`_EXPECTED_ANCHOR_HEIGHT` — always before
    any paid job, per this task's explicit "0 paid jobs on anchor
    validation failure" requirement. This calibration harness never
    generates an anchor itself; this is the only validation an anchor
    ever receives here."""


def _sha256_of_file(path: str) -> str:
    return hashlib.sha256(Path(path).read_bytes()).hexdigest()


class CalibrationAnchor(BaseModel):
    """The supplied, immutable anchor for a calibration run. Never
    generated by this module — always supplied externally (e.g. a
    real `frame0001.png` from a prior live acceptance run)."""

    model_config = ConfigDict(frozen=True)

    path: str = Field(..., min_length=1, description="Local path to the supplied anchor image.")
    sha256: str = Field(..., min_length=64, max_length=64, description="SHA256 of the anchor file's exact bytes.")
    width: int = Field(..., gt=0)
    height: int = Field(..., gt=0)
    original_seed: int = Field(
        ..., description="The anchor's own historical generation seed, as reported by the caller — this "
        "calibration run does not (and cannot) verify this against anything; it's recorded for evidence "
        "traceability back to whatever prior run actually produced this anchor.",
    )


class CalibrationShotPlan(BaseModel):
    """What `prepare()` planned for one shot, before any generation."""

    model_config = ConfigDict(frozen=True)

    timeline_index: int = Field(..., ge=0)
    shot_id: str = Field(..., min_length=1)
    prompt: str = Field(..., min_length=1, description="The exact, unmodified Prompt 13 reference-edit prompt.")
    planned_flux_seed: int = Field(..., description="derive_shot_seed(fight_base_visual_seed, this exact prompt).")


class ReferenceSeedCalibrationPlan(BaseModel):
    """Computed with zero ComfyUI/network calls — safe for dry-run."""

    model_config = ConfigDict(frozen=True)

    run_id: str = Field(..., min_length=1)
    fight_base_visual_seed: int = Field(...)
    anchor: CalibrationAnchor = Field(...)
    selected_shot_indices: list[int] = Field(..., min_length=1)
    shots: list[CalibrationShotPlan] = Field(..., min_length=1)
    expected_comfyui_jobs: int = Field(..., description="Always 2 for the default two-shot calibration.")


class CalibrationShotResult(BaseModel):
    """What actually happened for one shot."""

    timeline_index: int
    shot_id: str
    reference_anchor_path: str
    reference_anchor_sha256: str
    prompt: str
    planned_flux_seed: int
    actual_flux_seed: int
    output_path: str


class ReferenceSeedCalibrationResult(BaseModel):
    plan: ReferenceSeedCalibrationPlan
    shot_results: list[CalibrationShotResult] = Field(..., min_length=1)


class ReferenceSeedCalibrationRunner:
    """Drives the two-shot, derived-seed calibration experiment.

    `reference_provider` is required at `execute()` time (not
    construction), matching `ReferenceContinuityAcceptanceRunner`'s
    own established pattern (Sprint 4 Prompt 13) — there's no
    meaningful mock equivalent for reference-conditioned generation to
    exercise at construction time.
    """

    def __init__(self, ai_provider, asset_manager: AssetManager | None = None) -> None:
        self._orchestrator = FightOrchestrator(ai_provider)
        self._asset_manager = asset_manager or AssetManager()

    async def prepare(
        self,
        pgn: str,
        preferences: BattlePreferences,
        anchor_path: str,
        anchor_original_seed: int,
        style: str,
        battle_mode: str,
        shot_indices: tuple[int, int] = (1, 2),
    ) -> ReferenceSeedCalibrationPlan:
        """Validates the supplied anchor and plans both shots' derived
        seeds. Makes ComfyUI/network calls for none of this — only
        local file reads (the anchor) and the real, local
        FightOrchestrator/PGN-analysis pipeline (no network either).

        Args:
            pgn: PGN text of the game to analyze.
            preferences: Style/battle-mode preferences.
            anchor_path: Local path to the existing, already-generated
                canonical anchor. Never generated by this method.
            anchor_original_seed: The anchor's own historical
                generation seed (recorded for evidence, not verified).
            style: Must match whatever style produced the supplied
                anchor and the fight's own base seed derivation.
            battle_mode: Same reasoning as `style`.
            shot_indices: Which two timeline shots to reference-
                condition. Defaults to (1, 2) — the same two shots the
                live Prompt 13.1 GPU run reference-conditioned.

        Returns:
            A ReferenceSeedCalibrationPlan.

        Raises:
            AnchorValidationError: If the anchor is missing, unreadable,
                or not exactly 1280x704 — before any paid job.
        """
        self._validate_anchor(anchor_path)
        anchor = CalibrationAnchor(
            path=anchor_path, sha256=_sha256_of_file(anchor_path),
            width=_EXPECTED_ANCHOR_WIDTH, height=_EXPECTED_ANCHOR_HEIGHT, original_seed=anchor_original_seed,
        )

        generate_response = await self._orchestrator.generate_fight(pgn, preferences)
        timeline = generate_response.prompted_timeline
        selected_shots = [timeline.shots[i] for i in shot_indices]

        base_seed = derive_fight_base_visual_seed(pgn, style, battle_mode)
        shot_plans = []
        for idx, shot in zip(shot_indices, selected_shots, strict=True):
            # Sprint 4 Prompt 13's own unchanged reference-edit prompt
            # composition — this experiment isolates the seed variable
            # only; the prompt wording is deliberately untouched.
            prompt = compose_reference_edit_prompt(shot)
            planned_seed = derive_shot_seed(base_seed, prompt)
            shot_plans.append(
                CalibrationShotPlan(
                    timeline_index=idx, shot_id=shot.shot_id, prompt=prompt, planned_flux_seed=planned_seed,
                )
            )

        return ReferenceSeedCalibrationPlan(
            run_id=f"calibration_{uuid.uuid4().hex}",
            fight_base_visual_seed=base_seed,
            anchor=anchor,
            selected_shot_indices=list(shot_indices),
            shots=shot_plans,
            expected_comfyui_jobs=len(shot_plans),
        )

    async def execute(
        self, plan: ReferenceSeedCalibrationPlan, reference_provider: ComfyUIImageProvider,
    ) -> ReferenceSeedCalibrationResult:
        """Runs both reference-conditioned generations, sequentially,
        both against the identical `plan.anchor.path` — never
        chained, never regenerating or replacing the anchor.

        Args:
            plan: A plan from `prepare()`.
            reference_provider: A real `ComfyUIImageProvider`.

        Returns:
            A ReferenceSeedCalibrationResult. Per this task's explicit
            failure semantics: if the first shot succeeds and the
            second fails, the exception propagates (this method never
            returns a result claiming success), but the first shot's
            own output file remains on disk — the loop is sequential,
            so the first call has already completed and written its
            file before the second call's exception is even raised.

        Raises:
            ImageProviderError: If any reference-conditioned call
                fails. Never falls back to T2I, never retries.
            SeedEvidenceMismatchError: If a shot's actual
                provider-reported seed disagrees with what was
                planned — reusing the same evidence-integrity
                exception Sprint 4 Prompt 12.1 established, not a
                duplicate.
        """
        # Sprint 4 Prompt 14's own explicit requirement: an isolated
        # calibration directory, NOT nested under the normal
        # acceptance output tree. AssetManager.fight_directory()
        # always prefixes with "renders/" (its own established,
        # unrelated convention) — deliberately not reused here, so
        # calibration output never lands under storage/renders/ at
        # all, keeping it clearly separate from the existing
        # acceptance outputs it must not write over. Uses the injected
        # asset_manager's own storage_root (not a fresh get_settings()
        # call) so tests injecting a tmp_path-based AssetManager for
        # isolation are genuinely respected here too.
        output_dir = self._asset_manager.storage_root / "reference_calibration" / plan.run_id
        output_dir.mkdir(parents=True, exist_ok=True)

        shot_results = []
        for shot_plan in plan.shots:
            try:
                result = await reference_provider.generate_reference_conditioned_image(
                    shot_plan.prompt, plan.anchor.path, width=plan.anchor.width, height=plan.anchor.height,
                )
            except ImageProviderError:
                raise  # no fallback, no retry — see this method's own docstring

            actual_seed = result.metadata.get("seed")
            if actual_seed != shot_plan.planned_flux_seed:
                raise SeedEvidenceMismatchError(
                    f"Calibration shot at timeline index {shot_plan.timeline_index} "
                    f"(shot_id={shot_plan.shot_id!r}): planned FLUX seed {shot_plan.planned_flux_seed} "
                    f"does not match the actual provider-reported seed {actual_seed}."
                )

            output_path = output_dir / f"reference_shot_{shot_plan.timeline_index}.png"
            output_path.write_bytes(Path(result.image_path).read_bytes())

            shot_results.append(
                CalibrationShotResult(
                    timeline_index=shot_plan.timeline_index, shot_id=shot_plan.shot_id,
                    reference_anchor_path=plan.anchor.path, reference_anchor_sha256=plan.anchor.sha256,
                    prompt=shot_plan.prompt, planned_flux_seed=shot_plan.planned_flux_seed,
                    actual_flux_seed=actual_seed, output_path=str(output_path),
                )
            )
            logger.info(
                "Calibration: shot %d reference-conditioned against %s (seed %d).",
                shot_plan.timeline_index, plan.anchor.path, actual_seed,
            )

        return ReferenceSeedCalibrationResult(plan=plan, shot_results=shot_results)

    def _validate_anchor(self, anchor_path: str) -> None:
        if not Path(anchor_path).exists():
            raise AnchorValidationError(f"Supplied anchor not found: {anchor_path!r}.")
        try:
            with Image.open(anchor_path) as image:
                image.verify()
        except Exception as exc:
            raise AnchorValidationError(f"Supplied anchor is not a valid, readable image: {exc}") from exc
        with Image.open(anchor_path) as image:
            actual_width, actual_height = image.size
        if (actual_width, actual_height) != (_EXPECTED_ANCHOR_WIDTH, _EXPECTED_ANCHOR_HEIGHT):
            raise AnchorValidationError(
                f"Supplied anchor is {actual_width}x{actual_height}, expected "
                f"{_EXPECTED_ANCHOR_WIDTH}x{_EXPECTED_ANCHOR_HEIGHT} — refusing to submit any paid job "
                "against a mismatched anchor. No resizing, no fallback."
            )
